### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by GoobertFroobert** [LivingFray/HaloCEVR#14]
Who the hell just has the **original** Halo: Combat Evolved... just... _lying_ around? Why develop a mod for an ancient game instead of the one... That... I don't know... **millions** of people have access to?

**Comment by Minak-Kru** [comment]
If you read the FAQ, he mentions this as literally the first item...

Why the gearbox port and not MCC?
Short answer: skill issue.

Long answer: This mod my first time attempting to reverse engineer and mod a close sourced game engine requiring learning how to decompile, analyse and patch x86 assembly. As you may guess, this is hard. By focusing on an older title I have a simpler project to work with as I do not have an additional 2 decades worth of updates and advances in technology to worry about.

(For example, no dual classic/aniversary graphics, no MCC launcher application separate to the halo1 game code, DirectX9 rather than DirectX11, x64, simpler code layout with few virtual functions to follow (which I struggled to analyse in Ghidra).
